### ISSUE TITLE
Can't install flash-message-toast on window

### ISSUE THREAD

**Issue by sydenhong** [haojia321/flash-message-toast#2]
Hello,

I have problem with install flash-message-toast on window. When i run command install, it show message Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.0/win32-x64-57_binding.node".

![photo_2018-08-10_12-47-36](https://user-images.githubusercontent.com/15409509/43940930-367e9f4c-9c9c-11e8-99f5-30876220a799.jpg)

**Comment by haojia321** [comment]
This could be a meteor upgrade issue.
